# .goreleaser.yaml
version: 2
project_name: yaml2hcl

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/scub/yaml2hcl/cmd.version={{.Version}}
      - -X github.com/scub/yaml2hcl/cmd.commit={{.Commit}}
      - -X github.com/scub/yaml2hcl/cmd.date={{.Date}}

archives:
  - formats: ["tar.gz"]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: ["zip"]

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

homebrew_casks:
  - name: yaml2hcl
    repository:
      owner: scub
      name: homebrew-tap

    directory: Casks
    homepage: "https://github.com/scub/yaml2hcl"
    description: "CLI tool to convert Helm values to HCL"
    license: "MIT"

    # Skip CI
    commit_msg_template: "ci: publishing release of {{ .ProjectName }} version {{ .Tag }}"

    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yaml2hcl"]
          end

