name: Verify and Publish Tag
on:
  push:
    branches:
      - main
      - "*alpha"
      - "*beta"

permissions:
  contents: read

env:
  GOLANG_VERSION: "1.27.2"

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    if: "!contains(github.actor, 'semantic-release-bot')"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GOLANG_VERSION }}
      - name: Verify tests pass
        run: go test ./... -v

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: verify
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: |
          npm install -g                    \
            semantic-release@25             \
            @semantic-release/changelog@6   \
            @semantic-release/git@10        \
            conventional-changelog-angular@8
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_TOKEN }}
        run: npx semantic-release